### PR TITLE
switch back to dev

### PR DESCRIPTION
**Pull request by mollux**
switch back to dev to ensure that requiring 4.x-dev of this repo returns the correct packages

### CODE REVIEW

**Comment by escopecz** [comment]
Wait wait, why is this necessary? How should the release process look like?

**Comment by mollux** [comment]
without this, the latest dev release of this branch (https://packagist.org/packages/mautic/recommended-project#4.x-dev) point to 4.4.7
There is no way you can test the latest dev version via a composer flow otherwise.
If you look at the commit log you'll see this has been done here before.

See also the explanation in https://github.com/mautic/recommended-project/pull/29

**Comment by mollux** [comment]
@escopecz see comment above (forgot to mention you)

**Review by escopecz — APPROVED** [review]
Thanks! 👍

**Pull request merged**
